# -*- coding: utf-8 -*-
"""PLR1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_gPDoHrYWhxdIEUkg4YHWnMUFo_U6NFp
"""

from openpyxl import load_workbook
from openpyxl.utils import get_column_letter
import pandas as pd

def find_merged_range(sheet, row, col):
    """
    Determine if a cell is part of a merged range in the sheet and return the range.

    Args:
        sheet (Worksheet): The worksheet to inspect.
        row (int): The row index of the cell to check.
        col (int): The column index of the cell to check.

    Returns:
        tuple: The (start_col, end_col) range of the merged cell or the original column
               if the cell is not merged.
    """
    cell = sheet.cell(row=row, column=col)
    for merged_range in sheet.merged_cells.ranges:
        if cell.coordinate in merged_range:
            return (merged_range.min_col, merged_range.max_col)
    return (col, col)  # Return the column itself if not merged

def main():
    # Load the workbook and target sheet
    file_path = 'path/to/lS_LR_FHB_AGR_PM.xlsx'  # Adjust to the actual path on your system
    wb = load_workbook(file_path)
    sheet = wb['FHB']

    # Define rows which have headers
    header_row1 = 1
    header_row2 = 2

    misaligned_headers_info = []

    # Iterate over each column starting from the 7th to identify potential misalignments
    for col_num in range(7, sheet.max_column + 1):  # starting from the 7th column
        merged_range1 = find_merged_range(sheet, header_row1, col_num)
        merged_range2 = find_merged_range(sheet, header_row2, col_num)

        # If the merged ranges in both header rows are not the same, it's a misalignment
        if merged_range1 != merged_range2:
            header1_value = sheet.cell(row=header_row1, column=col_num).value
            header2_value = sheet.cell(row=header_row2, column=col_num).value
            col_index = get_column_letter(col_num)
            misaligned_headers_info.append((col_index, header1_value, header2_value))

    # Print out misaligned headers
    if misaligned_headers_info:
        print("Misaligned headers:")
        for col_index, header1, header2 in misaligned_headers_info:
            print(f"Column: {col_index}, Row 1: {header1}, Row 2: {header2}")
    else:
        print("No misalignment detected.")

if __name__ == "__main__":
    main()
# Comments added using ChatGPT